### ISSUE TITLE
Request Support: Compress Level

### ISSUE THREAD

**Issue by septs** [martini-contrib/gzip#11]
https://github.com/martini-contrib/gzip/blob/master/gzip.go#L31

default is [DefaultCompression](https://golang.org/pkg/compress/gzip/#pkg-constants)
the compression ratio is too low

see https://golang.org/pkg/compress/gzip/#NewWriterLevel

**Comment by slogsdon** [comment]
@Septembers Following the code, it looks like the default compression level is 6 (from [`compress/flate`](https://github.com/golang/go/blob/master/src/compress/flate/deflate.go#L405) which `compress/gzip` uses) where 9 is the highest level of compression. I feel like that is a good balance between compression and speed, but if there is good reasoning behind increasing the compression level, I'd be alright with the increase to a higher level.

**Comment by EgorMatirov** [comment]
Oops, sorry for such spam.
